[package]
name = "client-native"
version = "0.1.0"
edition = "2021"

[dependencies]
client-common = { path = "../client-common" }
workflow-log = { path = "../../workflow-log" }
tokio = { version = "1.20.1", default-features = false, features = ['rt-multi-thread'] }